"""CRA CLI configuration management."""

import json
from pathlib import Path
from typing import Any

from pydantic import BaseModel, Field


class RuntimeConfig(BaseModel):
    """Runtime connection configuration."""

    url: str = "http://localhost:8420"
    timeout_ms: int = 30000


class TraceConfig(BaseModel):
    """Trace storage configuration."""

    directory: str = "./cra.trace"
    retention_days: int = 30
    streaming: bool = True


class PolicyConfig(BaseModel):
    """Policy configuration."""

    default_risk_tier: str = "medium"
    require_approval_for: list[str] = Field(default_factory=lambda: ["high"])


class CRAConfig(BaseModel):
    """CRA configuration."""

    cra_version: str = "0.1.0"
    runtime: RuntimeConfig = Field(default_factory=RuntimeConfig)
    trace: TraceConfig = Field(default_factory=TraceConfig)
    atlases: list[str] = Field(default_factory=list)
    policies: PolicyConfig = Field(default_factory=PolicyConfig)
    config_path: str | None = None


def find_config_file() -> Path | None:
    """Find the CRA config file.

    Searches in:
    1. Current directory
    2. Parent directories up to home

    Returns:
        Path to config file or None
    """
    current = Path.cwd()
    home = Path.home()

    while current >= home:
        config_path = current / "cra.config.json"
        if config_path.exists():
            return config_path
        current = current.parent

    return None


def get_config() -> CRAConfig:
    """Load the CRA configuration.

    Returns:
        CRAConfig instance (default if no config file found)
    """
    config_path = find_config_file()

    if config_path is None:
        return CRAConfig()

    with open(config_path) as f:
        data = json.load(f)

    config = CRAConfig(**data)
    config.config_path = str(config_path)
    return config


def save_config(config: CRAConfig, path: Path) -> None:
    """Save configuration to a file.

    Args:
        config: Configuration to save
        path: Path to save to
    """
    data = config.model_dump(exclude={"config_path"})
    with open(path, "w") as f:
        json.dump(data, f, indent=2)
        f.write("\n")


AGENTS_MD_TEMPLATE = """# CRA Agent Contract

## Core Rules

1. **Always resolve via CARP** before taking any action
2. **Never guess** tool usage or API behavior
3. **TRACE is authoritative** - LLM narration is not
4. **Respect TTLs** on context blocks
5. **Honor the denylist** - never attempt denied patterns

## Runtime

- **Endpoint:** {runtime_url}
- **Session:** Active sessions expire per TTL

## Execution Protocol

1. Request resolution for your task via `/v1/carp/resolve`
2. Review allowed actions and constraints
3. Execute only approved actions
4. Monitor TRACE output for confirmation

## Error Handling

- If an action fails, check TRACE for details
- Do not retry without re-resolution
- Report errors through the proper channels

---

*Generated by CRA CLI v{version}*
"""


def generate_agents_md(config: CRAConfig, version: str) -> str:
    """Generate agents.md content.

    Args:
        config: CRA configuration
        version: CRA version

    Returns:
        agents.md content
    """
    return AGENTS_MD_TEMPLATE.format(
        runtime_url=config.runtime.url,
        version=version,
    )
